version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: learnnode_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: node_auth
    ports:
      - "27017:27017"
    volumes:
      - source: mongodb_data
        target: /data/db
        type: volume
      - ./mongo-init:/docker-entrypoint-initdb.d 
    networks:
      - learnnode_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/node_auth --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node.js Application
  app:
    #if already built image is available use image: learnnode_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learnnode_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/node_auth
      - JWT_SECRET=supersecretkey
      - EMAIL_USER=psiva4064@gmail.com
      - EMAIL_PASSWORD=gcet iiyc tskh hxds
      - ADMIN_EMAIL=psiva4064@gmail.com
      - FRONTEND_URL=https://frontend-admin-panel-ecru.vercel.app/#/reset-password
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./asserts:/app/asserts
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - learnnode_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    name: learnnode_mongodb_data

networks:
  learnnode_network:
    driver: bridge